/*
This file is part of mzPivotGrid

Copyright (c) 2012-2014 mzSolutions & Software SRL

Contact:  http://www.mzsolutions.eu

Commercial Usage
Licensees holding valid commercial licenses may use this file in accordance 
with the Commercial Software License Agreement provided with the Software.
 
*/

/**
 * This should be subclassed in order to implement different export types.
 * It prepares the pivot data though.
 */
Ext.define('Mz.pivot.dataexport.Formatter', {
    /**
    * Which nodes should be exported? All of them or just the ones that are expanded?
    * 
    * @type Boolean
    */
    onlyExpandedNodes:  false,

    matrix:             null,
    config:             null,
    data:               null,

    /**
    *   Pass the data object generated by matrix.prepareDataForExport
    */
    constructor: function(config){
        var me = this;
        
        config = config || {};
        
        me.matrix = config.matrix;
        me.onlyExpandedNodes = config.onlyExpandedNodes;
        me.config = config.config;
        
        // format the data for export
        me.data = me.prepareData();
    },

    /**
     * Performs the actual formatting. This must be overridden by a subclass
     */
    format: Ext.emptyFn,
    
    /**
    * Prepare data for export.
    * 
    */
    prepareData: function(){
        var me = this,
            matrix = me.matrix,
            group, columns, headers, record, i, dataIndexes;
        
        if(!me.onlyExpandedNodes){
            me.setColumnsExpanded(matrix.topAxis.getTree(), true);
        }

        columns = Ext.clone(matrix.getColumnHeaders());
        headers = me.getColumnHeaders(columns, 0);
        dataIndexes = me.getDataIndexColumns(columns);

        if(!me.onlyExpandedNodes){
            me.setColumnsExpanded(matrix.topAxis.getTree());
        }
        
        group = me.extractGroups(matrix.leftAxis.getTree(), dataIndexes);
        
        Ext.apply(group, {
            columns:        headers,
            summary:        [],
            summaryText:    matrix.textGrandTotalTpl
        });
        
        record = matrix.preparePivotStoreRecordData({key: matrix.grandTotalKey});
        for(i = 0; i < dataIndexes.length; i++){
            group.summary.push(record[dataIndexes[i]] || '');
        }

        return group;
    },
    
    /**
    * @private
    * If we have to export everything then expand all top axis tree nodes temporarily
    * 
    * @param items
    * @param expanded
    */
    setColumnsExpanded: function(items, expanded){
        for(var i = 0; i < items.length; i++){
            if(Ext.isDefined(expanded)){
                items[i].backupExpanded = items[i].expanded;
                items[i].expanded = expanded;
            }else{
                items[i].expanded = items[i].backupExpanded;
                items[i].backupExpanded = null;
            }
            
            if(items[i].children){
                this.setColumnsExpanded(items[i].children, expanded);
            }
        }
    },
    
    /**
    * @private
    * Returns an array of column headers to be used in the export file
    * 
    * @param columns
    * @param level
    * 
    * @returns {Array}
    */
    getColumnHeaders: function(columns, level){
        var cols = [], i, obj;
        
        for(i = 0; i < columns.length; i++){
            obj = {
                text:   columns[i].text,
                level:  level
            };
            
            if(columns[i].columns){
                obj.columns = this.getColumnHeaders(columns[i].columns, level + 1);
            }
            cols.push(obj);
        }
        
        return cols;
    },
    
    /**
    * @private
    * Find all columns that have a dataIndex
    * 
    * @param columns
    * 
    * @returns {Array}
    */
    getDataIndexColumns: function(columns){
        var cols = [], i;
        
        for(i = 0; i < columns.length; i++){
            if(columns[i].dataIndex){
                cols.push(columns[i].dataIndex);
            }else if (Ext.isArray(columns[i].columns)){
                cols = Ext.Array.merge(cols, this.getDataIndexColumns(columns[i].columns));
            }
        }
        
        return cols;
    },
    
    /**
    * @private
    * Extract data from left axis groups.
    * 
    * @param items
    * @param columns
    * 
    * @returns {Object}
    */
    extractGroups: function(items, columns){
        var me = this,
            group = {},
            i, j, doExtract, item, row, record;
        
        for(i = 0; i < items.length; i++){
            item = items[i];
            
            if(item.record){
                group.rows = group.rows || [];
                
                row = [];
                for(j = 0; j < columns.length; j++){
                    row.push(item.record.get(columns[j]) || '');
                }
                group.rows.push(row);
                
            }else if(item.children){
                group.groups = group.groups || [];
                row = {};
                
                doExtract = me.onlyExpandedNodes ? item.expanded : true;
                if(doExtract){
                    row = me.extractGroups(item.children, columns);
                }

                Ext.apply(row, {
                    summary:        [],
                    summaryText:    item.getTextTotal(),
                    text:           item.name
                });
                
                record = me.matrix.preparePivotStoreRecordData(item);
                for(j = 0; j < columns.length; j++){
                    row.summary.push(record[columns[j]] || '');
                }
                
                group.groups.push(row);
            }
            
        }
        
        return group;
    }
    
    
});