ALTER TABLE DWSECURITYUSERTOSECURITYROLE
drop CONSTRAINT FK_DWSECURITYROLE_DWSECURITYUSERTOSECURITYROLE;

ALTER TABLE DWSECURITYUSERTOSECURITYROLE
ADD CONSTRAINT FK_DWSECURITYROLE_DWSECURITYUSERTOSECURITYROLE
    FOREIGN KEY (SECURITYROLEID)
    REFERENCES DWSECURITYROLE(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYUSERTOSECURITYROLE
drop CONSTRAINT FK_DWSECURITYUSER_DWSECURITYUSERTOSECURITYROLE;

ALTER TABLE DWSECURITYUSERTOSECURITYROLE
ADD CONSTRAINT FK_DWSECURITYUSER_DWSECURITYUSERTOSECURITYROLE
    FOREIGN KEY (SECURITYUSERID)
    REFERENCES DWSECURITYUSER(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYGROUPTOSECURITYROLE
drop CONSTRAINT FK_DWSECURITYROLE_DWSECURITYGROUPTOSECURITYROLE;

ALTER TABLE DWSECURITYGROUPTOSECURITYROLE
ADD CONSTRAINT FK_DWSECURITYROLE_DWSECURITYGROUPTOSECURITYROLE
    FOREIGN KEY (SECURITYROLEID)
    REFERENCES DWSECURITYROLE(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYGROUPTOSECURITYROLE
drop CONSTRAINT FK_DWSECURITYGROUP_DWSECURITYGROUPTOSECURITYROLE;

ALTER TABLE DWSECURITYGROUPTOSECURITYROLE
ADD CONSTRAINT FK_DWSECURITYGROUP_DWSECURITYGROUPTOSECURITYROLE
    FOREIGN KEY (SECURITYGROUPID)
    REFERENCES DWSECURITYGROUP(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYGROUPTOSECURITYUSER
drop CONSTRAINT FK_DWSECURITYUSER_DWSECURITYGROUPTOSECURITYUSER;

ALTER TABLE DWSECURITYGROUPTOSECURITYUSER
ADD CONSTRAINT FK_DWSECURITYUSER_DWSECURITYGROUPTOSECURITYUSER
    FOREIGN KEY (SECURITYUSERID)
    REFERENCES DWSECURITYUSER(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYGROUPTOSECURITYUSER
drop CONSTRAINT FK_DWSECURITYGROUP_DWSECURITYGROUPTOSECURITYUSER;

ALTER TABLE DWSECURITYGROUPTOSECURITYUSER
ADD CONSTRAINT FK_DWSECURITYGROUP_DWSECURITYGROUPTOSECURITYUSER
    FOREIGN KEY (SECURITYGROUPID)
    REFERENCES DWSECURITYGROUP(ID)
    ON DELETE CASCADE;

ALTER TABLE DWSECURITYUSER ADD THEME NVARCHAR2(256) NULL;

ALTER TABLE DWSECURITYCREDENTIAL
    ADD EXTERNALPROVIDERNAME NVARCHAR2(128) NULL;
