Ext.define('IIG.Texts', {
    systemMessage: "System message",
    loadData: "Load Data",
    templateOperations: "Template Operations",
    waitLoading: "Loading. Please wait",
    createTemplate: "Create Template",
    selectFieldsToProcessReport: "Select fields to process report",
    doYouRealyWantDelete: "Do you really want to delete template",
    selectTemplate: "Select template",
    generateReport: "Generate Report",
    editTemplate: "Edit Template",
    deleteTemplate: "Delete Template",
    selectVersions: 'Budget Versions',
    resetReportGenerationStatus: 'Reset Report Generation Status',
    export: "Export",
});